baseURL = "https://kolam.bangunan.co/"
languageCode = "id"
title = "Jual Kolam Terpal | Jual Kolam Terpal Berbagai Ukuran dan Model"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Kolam Terpal Berkualitas - Berbagai ukuran dan model kolam terpal untuk budidaya ikan dan keperluan lainnya, dengan harga bersaing dan kualitas terbaik."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual kolam terpal", "kolam terpal bulat", "kolam terpal kotak", "kolam terpal budidaya ikan", "kolam terpal murah", "custom kolam terpal"]
  base_price = 300000
  price_range = 150000
  free_shipping = true
  materials = [
  "Kolam Terpal Bulat",
  "Kolam Terpal Kotak",
  "Kolam Terpal Custom",
  "Kolam Terpal Budidaya Ikan",
  "Rangka Kolam Terpal"
  ]
  categories = ["Kolam Terpal Bulat", "Kolam Terpal Kotak", "Kolam Terpal Custom", "Kolam Terpal Budidaya Ikan"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = [
    "Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Bandung", "Cimahi", "Sukabumi", "Cirebon", "Garut", "Tasikmalaya", "Sumedang", "Subang", "Karawang", "Purwakarta", "Cianjur", "Majalengka", "Indramayu", "Kuningan", "Banjar", "Pangandaran", "Kabupaten Bandung", "Kabupaten Bogor", "Kabupaten Bekasi", "Kabupaten Cirebon", "Kabupaten Garut", "Kabupaten Indramayu", "Kabupaten Karawang", "Kabupaten Kuningan", "Kabupaten Majalengka", "Kabupaten Pangandaran", "Kabupaten Purwakarta", "Kabupaten Subang", "Kabupaten Sukabumi", "Kabupaten Sumedang", "Kabupaten Tasikmalaya", "Serang", "Cilegon", "Tangerang Selatan", "Lebak", "Pandeglang", "Kabupaten Tangerang", "Kabupaten Serang", "Semarang", "Surakarta", "Magelang", "Salatiga", "Pekalongan", "Tegal", "Cilacap", "Purwokerto", "Pati", "Jepara", "Kudus", "Demak", "Blora", "Grobogan", "Kendal", "Temanggung", "Wonosobo", "Purworejo", "Kabupaten Magelang", "Kabupaten Boyolali", "Kabupaten Klaten", "Kabupaten Sragen", "Kabupaten Karanganyar", "Kabupaten Sukoharjo", "Kabupaten Wonogiri", "Kabupaten Pati", "Kabupaten Blora", "Kabupaten Grobogan", "Kabupaten Kudus", "Kabupaten Jepara", "Kabupaten Demak", "Kabupaten Batang", "Kabupaten Pekalongan", "Kabupaten Pemalang", "Kabupaten Tegal", "Kabupaten Brebes", "Kabupaten Cilacap", "Kabupaten Banyumas", "Kabupaten Purbalingga", "Kabupaten Banjarnegara", "Kabupaten Kebumen", "Kabupaten Temanggung", "Kabupaten Wonosobo", "Kabupaten Kendal", "Kabupaten Semarang", "Kabupaten Purworejo", "Surabaya", "Malang", "Batu", "Blitar", "Kediri", "Mojokerto", "Madiun", "Pasuruan", "Probolinggo", "Jember", "Lumajang", "Bondowoso", "Banyuwangi", "Situbondo", "Ngawi", "Magetan", "Pacitan", "Ponorogo", "Trenggalek", "Tulungagung", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kabupaten Lamongan", "Kabupaten Bojonegoro", "Kabupaten Tuban", "Kabupaten Jombang", "Kabupaten Nganjuk", "Kabupaten Madiun", "Kabupaten Magetan", "Kabupaten Ngawi", "Kabupaten Pacitan", "Kabupaten Ponorogo", "Kabupaten Blitar", "Kabupaten Tulungagung", "Kabupaten Kediri", "Kabupaten Malang", "Kabupaten Probolinggo", "Kabupaten Pasuruan", "Kabupaten Lumajang", "Kabupaten Jember", "Kabupaten Bondowoso", "Kabupaten Banyuwangi", "Kabupaten Situbondo"
  ]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Penggantian atau pengembalian gratis untuk barang dengan cacat produksi.",
  "Barang yang tidak sesuai pesanan dapat dikembalikan tanpa biaya tambahan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jual Kolam Terpal Berkualitas"
  hero_description = "Kami menawarkan berbagai pilihan kolam terpal berkualitas dengan berbagai ukuran dan model. Solusi terbaik untuk budidaya ikan, penampungan air, dan berbagai kebutuhan lainnya, dengan material yang kuat dan tahan lama."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Kolam Terpal"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan berbagai jenis kolam terpal berkualitas tinggi dengan berbagai ukuran dan model yang sesuai dengan kebutuhan Anda. Produk kami tahan lama, mudah dipasang, dan cocok untuk budidaya ikan atau keperluan lainnya. Layanan pengiriman tersedia di seluruh Indonesia, dengan konsultasi gratis untuk membantu Anda memilih kolam yang tepat."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "Kolam.bangunan.co menawarkan berbagai pilihan kolam terpal berkualitas dengan berbagai ukuran dan model. Kami mengutamakan kepuasan pelanggan dengan produk yang tahan lama, mudah dipasang, dan harga yang bersaing. Pilih kami untuk kebutuhan kolam terpal Anda."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Deni|Rudi|Hendra|Agus|Wawan|Rio}"
  message = "{Saya membeli kolam terpal dari kolam.bangunan.co untuk {budidaya ikan|proyek perikanan}, dan hasilnya {sangat memuaskan|memenuhi harapan|luar biasa}. {Kualitasnya bagus|Kolamnya berkualitas} dan {mudah dipasang|pemasangannya praktis|proses instalasinya cepat}.|Layanan kolam.bangunan.co {sangat baik|memuaskan|hebat}, kolam terpal yang saya beli {berkualitas|tahan lama} dan {mudah dipasang|cepat terpasang}.}"
  response = "{Terima kasih atas kepercayaannya! Kami senang dapat menyediakan kolam terpal {berkualitas|unggul|terbaik} untuk {kebutuhan budidaya|proyek perikanan} Anda.|Kami sangat menghargai kepercayaan Anda. Terima kasih}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Lina|Fitri|Diah|Nur|Maya}"
  message = "{kolam.bangunan.co sangat {membantu|mempermudah} dalam memilih {ukuran|dimensi} dan {jenis|tipe} kolam terpal yang {tepat|sesuai} untuk {usaha|proyek} budidaya saya. Produk yang saya dapatkan {berkualitas|sangat baik|memenuhi kebutuhan} dan {sesuai|cocok} dengan keperluan saya.|Saya {sangat terbantu|puas|terkesan} dengan layanan kolam.bangunan.co. Kolam terpal yang saya pilih {berkualitas|kokoh|handal} dan sesuai dengan kebutuhan saya.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan kolam terpal dari kami.|Terima kasih banyak atas ulasannya. Kami bangga dapat membantu usaha budidaya Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Faisal|Galih|Rizal|Bambang|Ali|Fajar|Toni}"
  message = "{Kolam terpal dari kolam.bangunan.co {sangat kuat|kokoh|tahan lama} dan cocok untuk {proyek|usaha} budidaya ikan saya. Proses pengirimannya {cepat|efisien|aman} dan {terjamin|lancar}.|Saya {sangat puas|terkesan} dengan kolam terpal dari kolam.bangunan.co. Pengirimannya {sangat cepat|teratur|efisien} dan kolamnya {kuat|berkualitas tinggi}.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan kolam terpal {berkualitas|terbaik} dengan {layanan unggul|pelayanan prima}.|Kami senang bisa memenuhi kebutuhan Anda! Terima kasih atas kepercayaannya.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Toni|Hendra|Dedi|Gilang|Ari|Wawan|Gani|Yudi}"
  message = "{Saya {sangat puas|terkesan|senang} dengan kolam terpal dari kolam.bangunan.co. {Kualitas|Mutu} kolamnya {sangat baik|unggul|luar biasa} dan {tahan lama|awet} untuk {usaha|proyek} budidaya ikan saya.|Kolam terpal dari kolam.bangunan.co {berkualitas|kokoh|tahan lama} dan sesuai dengan {kebutuhan|keperluan} budidaya ikan saya.}"
  response = "{Senang mendengar Anda puas dengan kolam terpal kami. Terima kasih atas kepercayaannya!|Kami sangat menghargai kepercayaan Anda. Terima kasih sudah memilih layanan kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan kolam.bangunan.co {sangat memuaskan|luar biasa|hebat}. Kolam terpal yang saya {beli|pesan} {sangat berkualitas|berkualitas tinggi|handal} dan sesuai dengan {harapan|ekspektasi|keinginan} saya.|Saya {senang|terkesan|puas} dengan layanan dari kolam.bangunan.co. Kolam terpalnya {berkualitas|kokoh|tahan lama} dan sesuai dengan kebutuhan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani} Anda dengan kolam terpal terbaik.|Kami sangat menghargai ulasan Anda. Terima kasih telah mempercayakan proyek Anda kepada kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Deni|Rizal|Rio|Benny|Yanto|Galih|Toni|Faisal|Wawan}"
  message = "{Kolam terpal dari kolam.bangunan.co sangat {sesuai|tepat|cocok} dengan kebutuhan {proyek|usaha} budidaya ikan saya. Pengirimannya {cepat|aman|efisien} dan {terjamin|lancar|rapi}.|Saya {puas|terkesan|senang} dengan kolam terpal dari kolam.bangunan.co. Layanan pengirimannya {profesional|cepat|efisien} dan sesuai dengan kebutuhan proyek saya.}"
  response = "{Kami {senang|gembira} mendengar bahwa Anda puas dengan produk kolam terpal kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan proyek Anda kepada kami. Kami senang Anda puas dengan hasilnya.}"
  rating = 4

[[params.tabelItems]]
  name = "Kolam Terpal Diameter 2, Tinggi 1 m"
  price = "795.000 /unit"
[[params.tabelItems]]
  name = "Kolam Terpal Diameter 2,5, Tinggi 1 m"
  price = "940.000 /unit"
[[params.tabelItems]]
  name = "Kolam Terpal Diameter 3, Tinggi 1 m"
  price = "1.000.000 /unit"
[[params.tabelItems]]
  name = "Kolam Terpal Diameter 3,5, Tinggi 1 m"
  price = "1.260.000 /unit"

[params.appliList]
  "Kolam Terpal Diameter 2, Tinggi 1 m" = "budidaya ikan, kolam sementara"
  "Kolam Terpal Diameter 2,5, Tinggi 1 m" = "budidaya ikan, kolam skala sedang"
  "Kolam Terpal Diameter 3, Tinggi 1 m" = "kolam untuk budidaya ikan konsumsi"
  "Kolam Terpal Diameter 3,5, Tinggi 1 m" = "kolam besar untuk budidaya ikan skala besar"

[params.kegunaanList]
  "Kolam Terpal Diameter 2, Tinggi 1 m" = "cocok untuk budidaya ikan kecil atau kolam sementara"
  "Kolam Terpal Diameter 2,5, Tinggi 1 m" = "digunakan untuk budidaya ikan skala menengah"
  "Kolam Terpal Diameter 3, Tinggi 1 m" = "dirancang untuk budidaya ikan konsumsi dengan kapasitas sedang"
  "Kolam Terpal Diameter 3,5, Tinggi 1 m" = "cocok untuk budidaya ikan skala besar atau keperluan komersial"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Jual Kolam Terpal Berbagai Ukuran dan Model | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"